### ISSUE TITLE
Error trying to jam a binary into a file (dynamic + stream)

### ISSUE THREAD

**Issue by lawik** [evadne/packmatic#11]
```
#! /usr/bin/env elixir
Mix.install([:packmatic])

[
  [
    source:
      {:dynamic,
       fn ->
         # Turn a binary into something Packmatic can pack
         {:ok, stream} = StringIO.open("a string\nfoo")
         my_stream = IO.binstream(stream, :line)

         {:ok, {:stream, my_stream}}
       end},
    path: "foo.txt"
  ]
]
|> Packmatic.build_stream()
|> Stream.run()
```

This produces an error:

```
** (CaseClauseError) no case clause matching: nil
    (packmatic 1.1.2) lib/packmatic/encoder/encoding.ex:67: Packmatic.Encoder.Encoding.encoding_next_data/2
    (packmatic 1.1.2) lib/packmatic/encoder.ex:126: Packmatic.Encoder.stream_encoding_next/1
    (packmatic 1.1.2) lib/packmatic/packmatic.ex:54: anonymous fn/1 in Packmatic.build_stream/2
    (elixir 1.12.1) lib/stream.ex:1531: Stream.do_resource/5
    (elixir 1.12.1) lib/stream.ex:649: Stream.run/1
```

I ended up working around it by building a custom type for straight binaries which I was surprised wasn't already there. Maybe I'm doing something wrong with the stream here but I figured better to report than not.

**Comment by evadne** [comment]
@lawik please try

https://github.com/evadne/packmatic/tree/feature/io-device

Will roll patch later if works

**Comment by lawik** [comment]
Seems to run clean, yeah :)

**Comment by lawik** [comment]
The underlying desire to deal with simple binaries captured here: https://github.com/evadne/packmatic/issues/12
