### ISSUE TITLE
Is it possible to use a directory as a file source?

### ISSUE THREAD

**Issue by aukuste** [evadne/packmatic#14]
Hi,

I tried the following in a phoenix controller:

```elixir
entries = [
  [source: {:file, "/home/user/test"}, path: "test"]
]

stream = Packmatic.build_stream(entries)

Packmatic.Conn.send_chunked(stream, conn, "download.zip")
```

The file path that is specified is a directory filled with files, but when accessing the controller via the specified route in router.ex, the result is a 0 byte zip file, and an exception is raised:

```elixir
[error] #PID<0.530.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.480.0>, stream id 3) terminated
Server: localhost:4000 (http)
Request: GET /download
** (exit) an exception was raised:
    ** (Packmatic.StreamError) unable to construct Stream due to underlying error
        (packmatic 1.1.3) lib/packmatic/packmatic.ex:57: anonymous fn/1 in Packmatic.build_stream/2
        (elixir 1.15.4) lib/stream.ex:1626: Stream.do_resource/5
        (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
        (streamtest 0.1.0) lib/streamtest_web/controllers/page_controller.ex:1: StreamtestWeb.PageController.action/2
        (streamtest 0.1.0) lib/streamtest_web/controllers/page_controller.ex:1: StreamtestWeb.PageController.phoenix_controller_pipeline/2
        (phoenix 1.7.9) lib/phoenix/router.ex:432: Phoenix.Router.__call__/5
        (streamtest 0.1.0) lib/streamtest_web/endpoint.ex:1: StreamtestWeb.Endpoint.plug_builder_call/2
        (streamtest 0.1.0) deps/plug/lib/plug/debugger.ex:136: StreamtestWeb.Endpoint."call (overridable 3)"/2
        (streamtest 0.1.0) lib/streamtest_web/endpoint.ex:1: StreamtestWeb.Endpoint.call/2
        (phoenix 1.7.9) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.10.0) /home/user/code/elixir/phoenix/streamtest/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.10.0) /home/user/code/elixir/phoenix/streamtest/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.10.0) /home/user/code/elixir/phoenix/streamtest/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

Are directories not supported for the file source? Do I have to walk the directory myself and generate a list of entries specifying each and every file?

**Comment by evadne** [comment]
Hello, thanks for your comment

At the moment each Source is responsible for a single file SO yes you should have to walk the directory yourself for now.

I believe Packmatic.Manifest.prepend/2 would be the best option for now until we work out how to dynamically expand the list of entries as we work down the Manifest

At the same time some may believe Packmatic.Source.File.validate/1 shall be enhanced to check the target exists and is a file… However the Manifest as currently designed allows you to just make a Manifest that points to a file that WILL EXIST at runtime, and to tighten that, would break use cases and force people to have things ready ahead of time, which is not the way.

**Comment by aukuste** [comment]
Alright, thank you for the information.
